sudo: required

services:
  - docker

install:
  - sudo apt-get update 
  - sudo apt-get install kubectl
  - wget https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-211.0.0-linux-x86_64.tar.gz
  - tar zxvf google-cloud-sdk-*.tar.gz google-cloud-sdk
  - ./google-cloud-sdk/install.sh --quiet

script:
  - echo $SERVICE_ACCOUNT_KEY_FILE > svc_keyfile.json
  - gcloud auth activate-service-account --key-file=svc_keyfile.json
  - ./build_and_deploy.sh $PROJECT_ID
